### ISSUE TITLE
Section 1: Introduction to MEX one small fix required

### ISSUE THREAD

**Issue by pajx** [DebugPrivilege/InsightEngineering#1]
"Let's filter only on processes that are running in session 3." - There you have command "!tl 3" which does not provide all processes with session 3 but all process names with number 3 in the name. I believe that the right command is "!tl -s 3".
Anyway, I would like to thank you a lot for such great job done and appreciate that you shared it with us!

**Comment by DebugPrivilege** [comment]
Nice catch, just solved it
